# group: deprecated-2017Q2
language: generic

matrix:
  include:
    - os: linux
      sudo: required
#      dist: trusty
      language: generic
      env: PYTHON="python3" PACKAGES="python3-cairo python3-gi python3-gi-cairo python3-sqlalchemy python3-psutil python3-websockets python3-pip stockfish"

install:
 - sudo apt-get update -q
 - sudo apt-get install -y xvfb gobject-introspection gir1.2-glib-2.0  gir1.2-gtk-3.0 gir1.2-rsvg-2.0 gir1.2-gtksource-3.0 $(echo $PACKAGES)
 - sudo pip3 install pexpect
 - sudo pip3 install coverage
 - sudo pip3 install codecov
 - sudo pip3 install flake8
# - virtualenv --python=$PYTHON --system-site-packages _venv
# - source _venv/bin/activate

script:
 - /usr/local/bin/flake8 --exclude=lib/pychess/external/ lib/pychess/
 - xvfb-run -a $PYTHON ./setup.py build sdist
 - cd testing
 - PYTHONPATH=../lib xvfb-run -a coverage run --omit=../lib/pychess/external/* --source ../lib -m unittest discover -p "*.py"
 - codecov
